# keeping it simple because this YML file is poorly documented/defined

build:
    stage: build
    script:
        - uname -a
        - autoheader -Iconfig
        - autoconf -Iconfig
        - ./configure
        - make local-install
    cache:
        untracked: true

test_mlrisc_seq:
    stage: test
    script:
        - BACKEND="" ./src/regression-tests/bash-scripts/run-seq.bsh

test_mlrisc_par:
    stage: test
    script:
        - BACKEND="" ./src/regression-tests/bash-scripts/run-par.bsh
