stages:
  - build
  - test
  - release

variables:
  GIT_SUBMODULE_STRATEGY: recursive  # download all, including benchmarks
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-test
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:pldi20

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

test:
  stage: test
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run -w /usr/pmlc $CONTAINER_TEST_IMAGE ./run_ci.sh local


release-image:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - pldi20
    # TODO: if you ever merge this into master, should change the name of branch
