# keeping it simple because this YML file is poorly documented/defined

build:
    stage: build
    script:
        - uname -a
        - autoheader -Iconfig
        - autoconf -Iconfig
        - ./configure
        - make local-install
    cache:
        untracked: true

test-mlrisc-seq:
    stage: test-mlrisc-seq
        - BACKEND="" ./src/regression-tests/bash-scripts/run-seq.bsh

test-mlrisc-par:
    stage: test-mlrisc-par
        - BACKEND="" ./src/regression-tests/bash-scripts/run-par.bsh
