# cache key for a ref on each job means that this job will check the cache for
# a directory image keyed on that thing, and if it exists, it will load that before
# executing the script. then it will save the image back under the same key when the job
# succeeds. so we copy-paste it all over


# for now this job tries to build the bare minimum of LLVM, to save time
llvm:
    stage: build
    script:
        - git submodule init llvm/src
        - git submodule update llvm/src
        - cd llvm/src
        - git log -n 1 HEAD
        - cd ..
        - mkdir build install
        - cd build
        - cmake -G "Ninja" -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD=host -DLLVM_USE_LINKER=gold ../src
        - ninja llc opt
        # skip install and use just build/bin
    cache:
        key: "$CI_BUILD_REF"
        paths:
            - llvm/build/bin
            - llvm/install

pmlc:
    stage: test
    script:
        - uname -a
        - autoheader -Iconfig
        - autoconf -Iconfig
        - ./configure --with-llvm=./llvm/build
        - make local-install
        - ./src/regression-tests/bash-scripts/run-seq.bsh
        - ./src/regression-tests/bash-scripts/run-par.bsh
    dependencies:
      - llvm
